services:
  _defaults:
    public: true
    autowire: true
    bind:
      $bundleConfig: '%huh_email2username%'

  # Event Listener
  HeimrichHannot\Email2UsernameBundle\EventListener\HookListener: ~

  # DataContainer
  HeimrichHannot\Email2UsernameBundle\DataContainer\MemberContainer: ~
  HeimrichHannot\Email2UsernameBundle\DataContainer\UserContainer: ~